name: DarumaSan
version: ${project.version}
main: net.kunmc.lab.darumasan.DarumaSan
api-version: 1.15
commands:
  daruma:
    description: daruma.
    usage: /<command> [おに(プレイヤー名)]
    permission: op
